#ifndef XUNO_VERSION_H
#define XUNO_VERSION_H

#define XUNO_MPV_MAJOR VER_MAJ_STRING
#define XUNO_MPV_MINOR VER_MIN_STRING
#define XUNO_MPV_PATCH VER_PAT_STRING

#ifdef WIN64
#define MPV_PLATFORM "x64"
#endif

#ifdef ARCH
#define MPV_PLATFORM "ARCH"
#endif

#ifdef __linux__
#define MPV_PLATFORM "Linux"
#endif





#ifdef MPV_PLATFORM
//#define XUNO_MPV_VERSION_STR  "v"
#define XUNO_MPV_VERSION_STR  "v" TOSTR(XUNO_MPV_MAJOR) "." TOSTR(XUNO_MPV_MINOR) "." TOSTR(XUNO_MPV_PATCH) " (" TOSTR(MPV_PLATFORM) ")"
#else
#define XUNO_MPV_VERSION_STR  "v." TOSTR(XUNO_MPV_MAJOR) "." TOSTR(XUNO_MPV_MINOR) "." TOSTR(XUNO_MPV_PATCH)
#endif

#define XUNO_MPV_VERSION_STR_LONG   XUNO_MPV_VERSION_STR " (" __DATE__ ", " __TIME__ ")"

#endif // XUNO_VERSION_H
